services:
  app:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: ./builder/local/Dockerfile
    container_name: asuransi-app
    volumes:
      - .:/var/www/html
    networks:
      - asuransi-network

  app-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: ./builder/prod/Dockerfile
    container_name: asuransi-app-prod
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - asuransi-network

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-asuransi
    profiles: ["dev"]
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - .:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app
    networks:
      - asuransi-network

  webserver-prod:
    image: nginx:stable-alpine
    container_name: nginx-asuransi-prod
    restart: always
    profiles: ["prod"]
    ports:
      - "8201:80" # 82 untuk nginx 01 untuk pengenal container
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
      - .:/var/www/html   # Menyambungkan folder app ke dalam container
    depends_on:
      - app-prod
    networks:
      - asuransi-network

  redis:
    image: redis:latest
    container_name: redis-asuransi
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
    networks:
      - asuransi-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-asuransi
    profiles: ["dev"]
    ports:
      - "8025:8025"     # Web UI
      - "1025:1025"     # SMTP
    networks:
      - asuransi-network

  adminer:
    image: adminer
    container_name: adminer-asuransi
    restart: always
    ports:
      - 8008:8080 # 88 untuk adminer 01 untuk pengenal container
    networks:
      - asuransi-network

networks:
  asuransi-network:
    driver: bridge
